services:
  medscreen:
    image: medscreen:latest
    build:
      context: .
      dockerfile: Dockerfile
      secrets:
        - HF_TOKEN
      args:
        HF_TOKEN: ${HF_TOKEN}
    container_name: medscreen
    ports:
      - "8501:8501"
      - "8502:8502"
    env_file:
      - .env
    environment:
      - PYTHONUNBUFFERED=1
      - NVIDIA_VISIBLE_DEVICES=all
      - PYTHONPATH=/app
      - HF_HOME=/app/huggingface_cache
      - HF_TOKEN=${HF_TOKEN}
      - GPU_MEMORY_UTILIZATION=${GPU_MEMORY_UTILIZATION:-0.94}
      - MAX_MODEL_LEN=${MAX_MODEL_LEN:-6144}
      - WINDOW_SIZE=${WINDOW_SIZE:-20}
      - N_WINDOWS=${N_WINDOWS:-5}
    restart: unless-stopped
    runtime: nvidia

secrets:
  HF_TOKEN:
    environment: HF_TOKEN
